package pt.ps.gamelog.Entities;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping // This means URL's start with / (after Application path)
public class MainController {
    @Autowired // This means to get the bean called playerRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PlayerRepository playerRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Player n = new Player();
        n.setPlayer_name(name);
        n.setPlayer_password(password);
        playerRepository.save(n);
        return String.format("Added player #%u %s %s", n.getPlayer_id(), n.getPlayer_name(), n.getPlayer_password());
    }

    @GetMapping
    public @ResponseBody Iterable<Player> getAllUsers() {
        // This returns a JSON or XML with the users
        return playerRepository.findAll();
    }


}